name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: SSH into EC2 server
        run: echo ${{ secrets.AWS_PUBLIC_DNS }}

      # Runs a set of commands using the runners shell
      - name: Move to API directory
        run: |
          echo Move to directory inside server.
          echo /opt/cooklens/api.
